services:
  client:
    build:
      context: ./client
    networks:
      - app-network
    depends_on:
      - nginx
      - auth

  auth:
    build:
      context: ./auth
    networks:
      - app-network
    ports:
      - "5000:5000"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - auth

networks:
  app-network:
    driver: bridge 